delimiter $$

CREATE TABLE `factor_fibo_levels` (
  `FACTOR_ID` int(11) NOT NULL,
  `LEVEL_FROM` decimal(10,3) NOT NULL,
  `LEVEL_TO` decimal(10,3) NOT NULL,
  PRIMARY KEY (`FACTOR_ID`),
  KEY `FACTOR_ID_FK_idx` (`FACTOR_ID`),
  CONSTRAINT `FACTOR_ID_FK` FOREIGN KEY (`FACTOR_ID`) REFERENCES `factor` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$