delimiter $$

CREATE TABLE `factor_archive` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FACTOR_ID` int(11) NOT NULL,
  `START_DATE` datetime NOT NULL,
  `OPEN_PRICE` double NOT NULL,
  `CLOSE_PRICE` double NOT NULL,
  `MIN_PRICE` double NOT NULL,
  `MAX_PRICE` double NOT NULL,
  `VOLUME` bigint(20) DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `START_DATE_UNIQUE` (`START_DATE`,`FACTOR_ID`),
  KEY `FACTOR_ARCHIVE_FACTOR_FK_idx` (`FACTOR_ID`),
  KEY `FACTOR_ARCHIVE_START_DATE` (`START_DATE`),
  CONSTRAINT `FACTOR_ARCHIVE_FACTOR_FK` FOREIGN KEY (`FACTOR_ID`) REFERENCES `factor` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=22559 DEFAULT CHARSET=utf8$$